### PR TITLE
ADR-0004: Graphics rendering tool

### PR DESCRIPTION
**Pull request by Earth34r**
This ADR proposes Two.js as the framework to render to HTML Canvas objects for our data visualization.

### CODE REVIEW

**Review by Y1kooo777 — APPROVED** [review]
nice work

**Review by lezhangleonard — APPROVED** [review]
This decision makes sense, in terms of the graphic interfaces we proposed

**Review by SirKanaad26 — APPROVED** [review]
Changed status to accepted - Two.JS works fine for our use case

**Review by jain-atishay — APPROVED** [review]
Using Two.js as the framework to render to HTML Canvas objects for tree visualization is a good idea

**Pull request merged**
