### PR TITLE
Merge tree rendering and tests to main

### LINKED ISSUE #54: Tree Visualization
- [ ] #55
- [ ] #79

### PR DESCRIPTION
**Pull request by lezhangleonard**
Closes #54 #55 #67

### CODE REVIEW

**Review by Earth34r — APPROVED** [review]
Passed locally and in github actions!!

**Review by Xcode-wu — DISMISSED** [review]
Good to go

**Review by jain-atishay — APPROVED** [review]
Works in local environment

**Review by Y1kooo777 — APPROVED** [review]
pretty nice work

**Review by Earth34r — APPROVED** [review]
Rebase headache, hopefully resolved

**Review by Y1kooo777 — APPROVED** [review]
good job

**Review by Xcode-wu — APPROVED** [review]
good to go

**Review by SirKanaad26 — APPROVED** [review]
Merge conflict resolved

**Pull request merged**
