### PR TITLE
Merging minor enhancements into main

### PR DESCRIPTION
**Pull request by SirKanaad26**

### CODE REVIEW

**Review by jain-atishay — APPROVED** [review]

**Review by Earth34r — DISMISSED** [review]
Good minor fixes

**Review by jain-atishay — DISMISSED** [review]
it looks more structured now

**Review by Earth34r — DISMISSED** [review]
Looks great, tests are fixed now, and everything is on the homepage

**Review by Earth34r — APPROVED** [review]
Looks good, minor changes and tests fixed

**Pull request merged**
