### PR TITLE
disable noAssignInExpressions and noParameterAssign

### LINKED ISSUE #63: Disable Biome noParameterAssign and noAssignInExpressions

### PR DESCRIPTION
**Pull request by lezhangleonard**
Closes #63 add skip arguments to disable noAssignInExpressions and noParameterAssign. Tested and works locally.

### CODE REVIEW

**Review by SirKanaad26 — APPROVED** [review]
Essential for linter

**Review by Earth34r — APPROVED** [review]
Tested it out, works great! Necessary to finish some of the open PRs.

**Review by Y1kooo777 — APPROVED** [review]

**Review by jain-atishay — APPROVED** [review]
Looks good as incremental step for using linter

**Review by Xcode-wu — APPROVED** [review]
Necessary for continuing success work

**Pull request merged**
