### PR TITLE
Add CI workflow with Node.js setup and test automation

### PR DESCRIPTION
**Pull request by jain-atishay**
This PR adds a CI workflow that:
- Runs on pull requests to main branch
- Sets up Node.js 20 with npm caching
- Installs dependencies
- Runs Biome checks and tests separately for better error tracking

### CODE REVIEW

**Review by SirKanaad26 — APPROVED** [review]
Running biome checks successfully and running npm tests successfully too. Node.js setup required for additional dependencies that may come up.

**Review by Xcode-wu — APPROVED** [review]
Approve

**Review by lezhangleonard — APPROVED** [review]
Good practice to run tests in separate steps

**Review by Earth34r — APPROVED** [review]
Good separation of actions for test and Biome check, allows for better distinction of which actions passed and failed on push.

**Pull request merged**
