### PR TITLE
Minor page size change for task-list

### PR DESCRIPTION
**Pull request by SirKanaad26**

### CODE REVIEW

**Review by Earth34r — DISMISSED** [review]
Awesome, the bottom being cut off was bugging me

**Comment by SirKanaad26** [comment]
I know, it kinda sucked

**Review by Earth34r — DISMISSED** [review]
Great README as well

**Review by lezhangleonard — APPROVED** [review]
I believe this is a good change

**Review by jain-atishay — DISMISSED** [review]

**Pull request closed without merging**
