### PR TITLE
Add ES6 style Jest+JSDOM testing env

### LINKED ISSUE #68: ES6 Jest + JSDom Testing Environment Setup

### PR DESCRIPTION
**Pull request by lezhangleonard**
Closes #68, add ES6 style babel and JSDom testing environment. Added dependencies. Tested locally with dummy testings and it works.

### CODE REVIEW

**Review by SirKanaad26 — APPROVED** [review]
Works well - have added jsdom for testing html

**Review by Xcode-wu — APPROVED** [review]
Approce for modification

**Review by jain-atishay — APPROVED** [review]
Using Jsdom in place of node does look like a goo alternative for testing HTML files

**Review by Y1kooo777 — APPROVED** [review]
Good testing method

**Pull request merged**
