### PR TITLE
Merge homepage and tests into main

### LINKED ISSUE #65: Tests for Tree artwork on page bottom
Testing the code for the svg artwork at the bottom of the page: issue #42

### PR DESCRIPTION
**Pull request by lezhangleonard**
Closes #65 #66 #40 #41 #42

### CODE REVIEW

**Review by Earth34r — COMMENTED** [review]
Is there any reason why we're using a .js file to store the quotes and not json?

**Review by SirKanaad26 — COMMENTED** [review]
The tests are based on the hardcoded components right now.
We need to revisit the tests every time we make changes to the homepage

**Review by Y1kooo777 — APPROVED** [review]
Successfully test html,css and js

**Comment by lezhangleonard** [comment]
Just update the tests for more general testing purpose

**Review by Earth34r — APPROVED** [review]
Looks good, removal of architecture-based tests. In a later sprint we should reword quote.js into a json object, and test a new method in quoteManager that loads it.

**Review by SirKanaad26 — APPROVED** [review]
Tests well written

**Review by commcheck396 — APPROVED** [review]
new home page looks great!

**Review by jain-atishay — APPROVED** [review]
Testing passes the need of coverage and the original plan

**Pull request merged**
