### PR TITLE
Add donut chart below the tree to show progress

### PR DESCRIPTION
**Pull request by commcheck396**

### CODE REVIEW

**Review by SirKanaad26 — APPROVED** [review]
Sounds about right. The graphs need to include percentages as the professor had told us.

**Review by jain-atishay — COMMENTED** [review]
Great work, pie chart look real nice

**Comment by jain-atishay** [comment]
If it is possible add the percentage of completion in between the charts

**Review by Earth34r — APPROVED** [review]
Tried it out locally, looks great

**Pull request merged**
