### PR TITLE
cicd diagram added #17

### PR DESCRIPTION
**Pull request by commcheck396**

### CODE REVIEW

**Review by SirKanaad26 — APPROVED** [review]
Diagrams look good, will keep updating if pipeline changes.

**Review by jain-atishay — APPROVED** [review]
I believe this diagram represents the current CI/CD pipeline for now and as we add more functionality this would be more enhanced.

**Review by lezhangleonard — APPROVED** [review]
Diagram looks much better than before

**Review by Y1kooo777 — APPROVED** [review]
good！

**Pull request merged**
