### PR TITLE
Add Jest and Biome dependencies

### PR DESCRIPTION
**Pull request by Earth34r**

### CODE REVIEW

**Review by jain-atishay — APPROVED** [review]
Looks good for initial setup

**Review by lezhangleonard — COMMENTED** [review]
Finally made it!!!

**Review by lezhangleonard — APPROVED** [review]

**Comment by Y1kooo777** [comment]
That's really good！

**Review by Y1kooo777 — COMMENTED** [review]
Good job!

**Review by Y1kooo777 — APPROVED** [review]

**Pull request merged**
