### PR TITLE
ADR to generate documentation using JS Doc

### PR DESCRIPTION
**Pull request by SirKanaad26**

### CODE REVIEW

**Review by Earth34r — APPROVED** [review]
Possibly add hyperlinks to the option names? It would make it easier to access the documentation for each tool.

**Comment by jain-atishay** [comment]
I believe it correctly mentions our progress and all the collective decisions we have taken to implement CD/CI pipeline till now.

**Review by jain-atishay — APPROVED** [review]
I believe it correctly mentions our progress and all the collective decisions we have taken to implement CD/CI pipeline till now.

**Review by jain-atishay — APPROVED** [review]
I believe it correctly mentions our progress and all the collective decisions we have taken to implement CD/CI pipeline till now.

**Review by lezhangleonard — APPROVED** [review]
Good pros and cons summary. The decision making process looks good.

**Review by commcheck396 — APPROVED** [review]

**Comment by SirKanaad26** [comment]
The ADR is satisfactory, JS Doc is the tool that shall be used for documentation.

**Pull request merged**
