### PR TITLE
About Us

### PR DESCRIPTION
**Pull request by SirKanaad26**

### CODE REVIEW

**Review by commcheck396 — DISMISSED** [review]
COOL

**Review by jain-atishay — APPROVED** [review]
Please correct the name as "Streek" otherwise it looks great

**Comment by SirKanaad26** [comment]
> Please correct the name as "Streek" otherwise it looks great

Fixed

**Review by Earth34r — APPROVED** [review]
Amazing about us page, looks and works great

**Review by Earth34r — DISMISSED** [review]
Looks awesome, great changes to css refactor as well. Love the avatars

**Review by Earth34r — APPROVED** [review]
Looks awesome once again

**Pull request merged**
